# Generated by Django 3.0.5 on 2020-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photoTeach',
            field=models.FileField(blank=True, upload_to='teachers/%Y/%m/%D'),
        ),
    ]
