# Generated by Django 3.0.5 on 2020-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatchingUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField(verbose_name=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('matiere', models.CharField(max_length=60)),
            ],
        ),
    ]
