# Generated by Django 3.0.5 on 2020-04-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchingup',
            name='Teach',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catchingup',
            name='numClass',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.Class'),
            preserve_default=False,
        ),
    ]
