# Generated by Django 3.0.5 on 2020-04-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_classid'),
        ('service', '0002_auto_20200416_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('topic', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='catchingup',
            name='roomNumber',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moyenne', models.FloatField(verbose_name=0.0)),
                ('Observations', models.CharField(max_length=100)),
                ('listNotes', models.CharField(max_length=100)),
                ('idR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
