# Generated by Django 3.0.5 on 2020-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=60)),
                ('cin', models.IntegerField(default=0)),
            ],
        ),
    ]
