# Generated by Django 3.0.5 on 2020-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photoStud',
            field=models.FileField(blank=True, upload_to='studentss/%Y/%m/%D'),
        ),
    ]
